# -*- coding: UTF-8 -*-

#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

clone = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABZ1J"
    "REFUWIXFl2tsHNUVx38za+/O7Hp3jfHuEtuBoDpBhWyFiRwlHypVBSKapChq2kYUhBAUEAof"
    "GuMggUiCQCpRaSPxsHlURRUE1DgWUrCIIgXFUqs8jR2ot05ir+3Ej0iJHdu7djye2cfhw4Zx"
    "lmTWmyLElUaae8895/zn/M85d66iqC5+zKH+qN6Bkv9XUbIZuTg2BkA4FEJRXcoPDkCyGYm8"
    "P2jPJ8YuUlNdQ/jV49wTrZG7Iy52rr7lhsAUTcGKfRekbs8QVUEXVUEXZZ6cj5HREXTdDcCZ"
    "S1ka/n2BXz36mEg2I8XYVYpJwlN9ffKnuAfvlXg9eVc5k5bwYDADQP2HQ1RGbqJ3KgXAmls1"
    "Ql/sYtdfX18wGkVFIBSJ8OI9Fayo1di2stJe9wUC+AIBNM1FVoMyj4JhZUlcGOE3Dz1UjOmF"
    "cyCbSQvAz33gn1GZUbJkvQopxbL36LqK36Mwq+W+50FPP4lkhJOxGHXLl0uhKNxQEuo6ZIHk"
    "LPiuUtX0UoK+K8GcgqpgOZNTU2iavqDNghQ4JVKlv5TIzfOq5eUalX6VoE/Fq6sEQmEAzMTU"
    "9wOwdt26vLmuqPhQKcmk8V6luqiyhDJNxaupLKsqpbK8nJt0nUnD+H4A7rv3l4yNj9vzW9Vc"
    "2H2o3Cal9vpPF3kIaCphv8oHK8JUBPx4guW07f8cXdcdI1kQwKnYfwVgw4YNeeuV4sJjwbiS"
    "oW0oSdtQkqqKEoL6fDm7dC8et5v9LXsBGOyPO4JwTEKPx8OWLQ3U/qQ2b10xTQJA0iqhujrX"
    "gCYVMHRIGLm+4C0twefJyeLxPqYTCSc3C/eBeH88b17h8wIQyKbxfUf9D6Ey+13Xvaxfv34h"
    "86Corus+gBimKSIix44elc/27ZNjR4+KiIhhmnJp5rKcTpvSmTbki4whn6ZnRETkhW3bJRQO"
    "S0PjVjkZi8lgf1wAAeR6fhwpUFSX8pedO2X79u2sWr0aXdeZmJri7eZmTvf0MHj2LB0dHWia"
    "xuLFiwHoXrOG5Xcs45ZIhLbP9vHU44/x1jvv2fau56cgBaXuHI+hcJgjHR1objdvvvEGTU1N"
    "RO/7BZ+eH+STgVPUrlrF8PAwx0+cIGWZdHd3EwqFFg4/C3TClGXxdnMzAK+/9hof795N75kz"
    "XEpnuLnEhaLkPkpE+OrlP1M9l2Ri7CLRaBQjZdGw9XluX7KkMAKnHGho3CqGacrf3222c+Hq"
    "0Zk2bG7PZVIyOjoiJ2Mx2X/ggLTubZH29nbZuHGjDPbHZdeuvznmgCMFr2x7iYMHDvDHp5/h"
    "666ua+SzZO33Q5PpXCTMOQDcbg9tn++ntbWVzq4uNm3a5BgARwAjoyP8q6WFy8kkQF5HBEjO"
    "XptTlpUibZp26Z4/P8qW5xrp7e1zBOCYAwNDwxw8eJC6+noOHz58jTygKjT1DnD7QC/nDMGy"
    "5vLkv163lurqGgBiPT03DmDtAw8wk0jg0jQyc3PMWvPnv6Io/PODf5A15ugH/OdHuXPzs7Qf"
    "OoRlmQAsW7aU9vZ2Yj09PN/YeOMAFNWlJGampULTcn8+wJxlMZ1McrrnfwDsceXa9P2ZOCc7"
    "v8QfDLI0+jMqfF7Gxsc5NzjAxPg4hmE49oGCZVhdXYPI/Bmiud0QCOAPBACYvkLtbUtr8/Zc"
    "TiZJWSalbg87duwo5KJwI1JUl3LmVD5/p/v6OHbkCADDEwq9FxTbseZ2M2dZJGam+bo7RuoK"
    "HQWHUx+4+kzo6vxSRETqVtZLNBoVwzRldHRE7vrorCx65z92b6hbWS91K+tFROzax6H+bfsL"
    "AVBUF281NcnmzZttg0De/Luyx594Qlr3thQFoKh7gWQz0rq3BdOcr4SHH3kkb8/Hu3cDkLJM"
    "yvx+fvu739s0FmSg2Nux0x/Ntw6uJy/milY0gB9qfAP7fHZJFDd6iAAAAABJRU5ErkJggg==")

clone_data = clone.GetData
clone_image = clone.GetImage
clone_bitmap = clone.GetBitmap
clone_icon = clone.GetIcon

red64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABqJJ"
    "REFUWIWtll9sFNcVh787M2sb7NqKXai3tjFg4kJrQGpABEEah+YBoqpIIUFR49SlRqgKciuq"
    "PlAixQj6AFUoSG2FhNMtiqKklXgC1IZGQCIREypDhVyxxjTx4hRMbP54be/OnZk79/Zh7Sm2"
    "1xRMjzTSaObOOd/8zrm/GYwxzORQr7HbrMOYZzC8QttM81jMNEYBMRtEUe58hvF4AJt2wPd/"
    "8lgAjyzZrl27tpaUlNwzv2kz5rtVxjTGjX6rzSxfvryrvr5+7aPme+iFBw4ceNv3fROGoTHG"
    "GPPrNmOexJhFGL2/zWitTRiGRkpp5s2b973/6wyEYTiyffv2Ftu2EUKMXQQ8QILQIlrrOA7d"
    "3d0nGhsbP3yY3P8TIBaL9UspS2zbntAywlxxPDDKTLjnOA4nTpx4/syZM288FsDx48fn9/b2"
    "VjqOM/WmyhXHy50bMxFCCEFNTc2vHgugpaXlqDEGKeWE5MYYjLZyCshcmkgZQCmF67oAzJo1"
    "q3FGAAsWLKj806tbntVaEwQB2WyWIAjuK2SDJ8AXGGNH17PZLK7rEoYhnZ2dPPX5zeYZAVy5"
    "cqW/tPszwjBEKUUQBNGbSSkJQggpJKQIXxlc1yWbzaKUig5jDO9+fOZHDwIQ47JNDimlWb1q"
    "NcUlJRSXlFD2RBkN32rgSncS6bq4Y0d0Ll1k1sWVEjebRUp5/1yIvEWAPNOVC8/z+CNlnPMN"
    "H8RsTBjy6fkOBgYGGBwcJJPJkMlkmDNnDv39/SilpuR4Y24tPzz82wcJMH0LPM9D/eEtXnz7"
    "d7xzqpNn/j1ALBajoKCAwsJCYrEYjuMwvj3vj60UcvuFl3n9Hx14T85/IMC0Cvi+n4OYO5fw"
    "Zhevnv87r218hd318zhlWdi2jWVZhGEYPfMCDu8sWYb++AOU1ijPw/f9R1dACCGGh4dJpa7n"
    "IJRCrVqBGvicNze9xCdXe5ljiFxxhYHbZXM4+kUv4Ud/jQZ3dHSUvr4+RGSfDwkAWFJKKirK"
    "SaVSjIyM/He6f/Y66lYfz7oulmWhteaXWKirXSjbjnaLUoqLFy9SVVX1QKWnA3CklJSVlfHe"
    "++8zOjoaKTFeYJ4KANBaUynCCdsvCAIGBwfp7OwkCAKAoulUmAIwttDxPA8pJdU1NZw69TfS"
    "6TRBEEQA1ToHEIYhX3MMvu/j+34EcfzkSWpra/E8D6AAyAswnTTW2IPU1dWBJUgmkyxevJiS"
    "khKEEMRREYDvgBlzSa01XV1dLKiro7y0dBwgNk2daQEc3/eprq6moaGBa9euMTIywtDQEAUF"
    "BQghKBcKrTVaa3wbjO/n/hWVQliCb9bXE4/HSSaTAIVjauspb5qnuACshQsXUlZWhtaapUuX"
    "sm7dOmzLZmBgAN/3eTEL6XSadDpN86iOWtDxyXmea3yOeDxONpulsrKSJUuWvDldC/ICbN68"
    "eZHv+8RiMYqLi9Fao5Ri1dOruHXrFmvWrKFHw+7mJra+/BIXQ1i7di1SSp5a8e2cCkIwe/Zs"
    "jDEkEokfA1MdizzfAiGEc+HChS8dxykvKCigqKiI8vLyyPUqKytpaGjg3BefIgQYAbqmjq/3"
    "pHEch2PHjlFfX4/neaTT6cjQEonEL9rb2w8aYya0wZpUXACxbdu2NY07nNaa4eFhMpkMmzZt"
    "Yu/evZw9exZVW0tgg3JAVVeRSqVYuXIliUSCTCZDNpuNhjIMQ9rb20+SZxjztaDw8uXLMplM"
    "Xrh79y5KKcIwpKOjg9bWVpqampBS4tXU4DkgLfDi1biuy5EjR3Achxs3bqC1RkrJ0NAQbW1t"
    "vweeAAon+0E+AAO4zc3Nf7l06dKXfX199PX1AbBs2bLIaIJ4daRAYIvIH3bu3MnRo0dJpVL0"
    "9/ezf//+c6dPn74KZIApn8wJMzDeAmAusBz4zpYtWzZ+IxfYtk08Hicej2O9exDeOZBrU9PP"
    "UT/4KdevX+fOnTuEYUgymSSRSHyYSqXOAOeAq8A9Y4yaFuA+iELgq8BiYEVpaenTBw8e3Dj+"
    "BbQsi56eHvbs2QPA4cOHo92itSadTssdO3b8GbgAXAI+A4YmF4c8RmSMMUIIDxgAfODe8PDw"
    "jZaWlp4NGzasXb9+/erxNsbj8ZwRjU267/vhoUOHTty8efMS8E+gG+gHRvMVz6vAJDUcYBa5"
    "AaoC5gOLKioq6lpbW5/XWlcB+L5/Zd++fR8BvcC/gBRwC0gD3uSt99AAYxCCnIkUAV8Bysm1"
    "pwIoHls2MqbYbeAeuYHzjDHhlIST4j9D0bJeChc6kAAAAABJRU5ErkJggg==")

clone_red_64_data = red64.GetData
clone_red_64_image = red64.GetImage
clone_red_64_bitmap = red64.GetBitmap
clone_red_64_icon = red64.GetIcon


old64 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAACURJ"
    "REFUWIWtlltsFOcVx3/fzN5s79rY4AvY8dLECGhMAuGSRpEa4lYh5CVSVQg8UKii0qYShYdU"
    "EXkgiD4k1C+plEj0oYmSqFEUJUhpkAKiFEowWDaOnBqCCQ7eBWzsXXsv3pmdnZ2dOX3w2iEO"
    "TlO1Rzra0c635///zv9cFhHh+/ro6GhwZGTkQCgUGstkMpLOZCWdzkgqlRarYJvHjx/vVEpF"
    "/puY3+vQiy++WO+KTNm2LZZti2VZYpp5MU1TTNMUwzDFMAyZyhmSSmVkPJmUQ4cOrf+/EDj7"
    "6aevmKYpxWJRHMeRouOIXSyKbduzXiwWxXVdcV1XCrYtqXRGEskJWbly5fn/iUAoEvl9Op0V"
    "254GL5VKs+44zqy7riue54mIiOMUxbIKYhiGJBJJeeSRR/7+XRhKRJjP0pmM+H1+AoEAmq6B"
    "gFLT79TMw5znmXgigmmamKbF+PjtqtWrV+fvhqHNB/7SSy/9RNM0NE0hCIiglJr1O+3OS0j5"
    "nKZp6LoPzafx2Wf/OjQfjm++Fx0dHT/1PG86qOeBpgHCLJZSKECmUe+4OXiehzD9qQDbNh+f"
    "D2feDHzwwdHfZtJZPBEEcD1vOvAMgznKTQMLnuvhui7FYhHP8zByBqdOnXlwPpx5ayAajUrX"
    "hQtEqiKIuLiux+3RUWI34iQTSRynCEohZWKVlZXULVxItLWVlpYWRBS6rmHkTR5/7DGuXbum"
    "7oZzVwJKqZKmafqMBDPm9/uprq6msrKSYDCIpmm4rkuhUMAwDHK5HCJCJBKhoqICXdexbZtU"
    "KoWIlETEPxfrWzWglFKBQMBbsWKFvnTpUuLxODU1NUQiEerq6lBKYZoma9asIRqNAhCPx+nr"
    "6yMSiQCQyWSwbRvLsohEIgwPDxOLxe4u99y+7OnpWe+6rvT398uJEycEEKWUhEIhqa+vl3vv"
    "vVdaWlqkv79f4vG4xONx6e/vl5aWFmlra5PGxkYJh8OiaZoA8tZbb0l3d7c4jiNjY2N/+I+D"
    "aPfu3R97nic3b92S3t5eWbp0qYTDYVmwYIHU1NQIIOfPnxfLsmaHj2EY0t3dLYBUV1dLbW2t"
    "hMNhCQaDcvr0aRkejonrulJfXz86F+9bablw4UKL63kgHtFolJMnT9Lc3Iyu6zz//PMUCgVq"
    "amqAr+eBruuEw2FyuRyHDx9G0zRaWlp47733aGtrY2Iiied5jIyMLPxOCQD16KOPnioUChKL"
    "xeTy5ctimubsnDcMQz788EMZGhoSy8rLjE1NTcnw8LCcPHlSstmsFItFKZVKYhiGDAwMyPHj"
    "x8UwDAGSgHbXDKjp6/hPnTr1F8uy8Pl8dHR0kM1mGR4e5qOPPuLs2bMsXtw8O+VmrFQqoZSi"
    "traWgYEBurq6uH79OpOTk3R2diIiOI7DM8888zHwjU64UwIFhDdv3lyXyUwRDAZJJBK8/vrr"
    "mIZJa2srTU1N1NUtIBAIoOv67FQMBoP4/X4aGhpoamqitbWVgN/P5OQk77zzDg899BCFgk06"
    "nS4AlUqpr3HvSH/g2Wefbbs5MlK6fGVQ8vm8bNy4UZLJpIyOjkosFpNYLCY3b96UiYkJyefz"
    "smvXLtm+fbtkMhlJpVKSSCQkkUjI5OSkZLNZyeVycvDgQbFtW64PxyQWuyFdXV3tQPAb27Cc"
    "/oqhoa8yOdPw+zSdpqZGqiMR7GKRUsnF81xEQNMUuVyOVatWkc/nCQQCiAhvv/02Tz755Oyy"
    "0jUdFOiaRsl1GRkZwTQtQhUh9v5uT82JEydyIiKzqYjH4w+nsxl/3YJafhBtJZ/P44ng8/sJ"
    "BgOEQiFCoSDZbJZVq1bR3t7Oa6+9xquvvsrGjRvZtm0b77//Pj6fD5/Ph6ZrKKUoOg63bt0i"
    "Eg6zaNFC8vk8W7Zs/1VZ8q8noW3b9xUsiy++muCi6fKbH1UxPDxMNBpF0zQUijNn/8nWLVsY"
    "Ghqirq5uWj7PY8eOHWiaRkVFBel0mj179iAiFAoF0uk0yeR0G/71c5vNrRbne87XUV5nvnL6"
    "9TfffPP06jVrWLSwjvTAEB8EfsjK4AQiQkNDA+3t7YRCIcbGxgBwXXe6EJXC8zwcxyGbzdLe"
    "3k5nZydD14ZIpVJc+eIKra2tHLuU4mbvJZKhJv529OiZ8uUdBehABFhx5Mif/1QqORvC1XVs"
    "WLuamuoImu7jjTffYOfOXxAKTS8YTdM4evQon3zyCX6/n46ODp5++mlcz8MtlZiYmGD//v0c"
    "OXJkdjV3XeglmxpHafrY3r17twGXgKwOBIBGYP2xY8eaRWTx1p//LFQqlSg6Do7j8OADD6DQ"
    "8FwXz3Wx8nl6ens5duwYiUSC9vvvn15MIhSLRTRNY9MTTzCVyzE1NUU2k6G2tobzF7qLBw8e"
    "7AEyQAKY8pW1UOWU+Hp7LxbzBYtgIIjreRiGwbvvvovf76e+vp6tW7cyODjIPffcw+3bt/E8"
    "j8VLlnD16lWWRqNc7OvjRvwGeSvPunXraGxsRDwPx3Xp67tolTPuu7MIXSANfAE0T0wkI8aU"
    "Ue9b4EP54NLAAGvXruXXu3ejlKKqqor72trYuXMnkUgEwzD4rK+Pjo4OBq8M8txzz1FyHJYt"
    "W8b9K1fieR6eCOPjCc6dO/cl0FdO/wTgaCLiAlPAVeA00HWuq2sknUmTy+Vobm6hqaEBBQQD"
    "AaojET7v78e2bfL5PCLCHzs7aWxqomZBDeFwGF3TqKutpWnJEkzDYHw8SSIxnge6yxiXgbSI"
    "uFp5GpbKunwF9L/yystnJicm3VwuR8ktUVNby44dO9i0aRNty5bhui5KKSzLmtU8mUxSUVHJ"
    "4Zdf5qmnNrNz1y8pFApks1PkLVP27dt3EugHvgRSIuLAHX/Jyu1YCbQBPwaeOHDgQEc0Gq0M"
    "BoOEw2FAmMrlSE2mvH379plKqcg0f0nv378/snz5cn9VZRVVVZWkJlMY+TzZbKb0wgsvnAH+"
    "AZwCBgFDRLxvECiT0IEwEAXWAg9rmrZ83br1rYsXN1WmUqliT0/Pbdu2E4BVLmAHKAJhpdTi"
    "DRsebq6vX1SZzWaLFy9evGVZ1mBZ995yhrNl2fkWgTIJrdyatUAz0AosAirKQJNlN8s/KZUL"
    "ubLcznPP3gJuAinAmrn5vATmEPGVyfiZbh8pB3aAmUAzn/odZ7Xy9yXABpy5wDP2b6cciZGo"
    "8nDkAAAAAElFTkSuQmCC")

clone_old_64_data = old64.GetData
clone_old_64_image = old64.GetImage
clone_old_64_bitmap = old64.GetBitmap
clone_old_64_icon = old64.GetIcon

jango32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAACDdJ"
    "REFUWIWll2twVNUdwH/n3r13N5vdTTYvQiAhMRsoPpBgfKBGmIGp1jq0TmVax04fttN+0A6i"
    "5QujnTpTFWWsjlOstR/q1NFolaLYWnwgFsHIQ5AkaMiTxCSbZB/Z9+7d3XtPPyRUEhaI43/m"
    "/+Gec8///zv/x7n3IKVkrvp8vlPbtz8hpZSyr69f9g8OyN7ePlno3W+qNgqIz+db6rA7eevf"
    "b5PLZQlMBtn22BP3DA72FHr9G4mQUp4zuGHDhiemwpEtHx3YL7xeb+XU1FTgzNzExETlkzt2"
    "3Pybh7eWjQ0PZw8fP8HBQ8e0htblqfduKtt71HXb6W8MUFNT86u2thevW7Nm3d1nxlJ15Tcn"
    "PuvZI4QgHIkSSyeJpZKkjDRZM8/EZIjRsVGmpsIcT0/9un3bjufnA6AUGqyrq3Pcf+/9NWee"
    "XbXV+8KHOvbYbBrhRJycMJECFEXBkpBOGdgddqqqF6C5nNSkrL88/s+XhucDULAGNm3a5Czx"
    "eEyAkGL9ZyzSs9bj8XC8txvNpmFJiaooODSdvEPiLHJgmSbZfBlLFi5in36YA+9/WHui/dDp"
    "l7c/U/+1ATZs3FilTiXeALCi8Vs87hKO9Z7CyBrkciamNMnn86SyGfKmhaYoWJagzOXmhhXN"
    "FDuL2C0V+ro6lmyf6r9ji7fx9fMBzEqBEMIGUO5y2fOW4dr0+CPd+VSGzoFeEskERj5H0kgS"
    "TcYJxmNkjCzZbJZc3kQokrwEfzDA5fWNtFx6KU2XXsY7mx987etEwC6EKD5y4IDjzf1779Ys"
    "ucw/NkZUWljCJJnIILGw2zQcqkYgFgEp0XUNIQThWJQjX5zEade5a/2tDE+MU3tJA+1PPlm2"
    "+oEHwheNAGACJbFU5o6eUwOXT6YihBULoVhk0jlS2RRj4SA15eV859rVhONR4qkU46Eg48EA"
    "/lCItJFiNBBA1zUWeEvRbXZ+KsdvmlcKAAOYbG5u9hQ7ikgk0nR0dqCodrJWDsuysCsaH3Yc"
    "56mdbSBUjLyBZUE8nSGdSaOpOijQfuIYFQ431ZfUEWjbGZpXCuT0oZABsLucDEwFqItECOx7"
    "l8b6BhxuN06nitAV0rEEhpFBsdnQdQ2nXceyJIqqUOwqZjQUJqvAhBA8uu2Z24GPCgEUPIg+"
    "7eySRz/YR6WuEmqo5eTgIP1DQzjsOtX19VRUVGKOjlC+eDFhKXHrdrDbME1ASlDBCkcpjcVJ"
    "v/8ev9yylZLmZq+UMnLBCJyR0fFJxgZPU/95J6uaV3FHUxOxa67nRFcnwx8fJqmoWCUl5Eb8"
    "VJoSzTIp0TQchoGWSOCKxlBDYfr8Y/yrs4vW625iV8/J94GWiwIIIcpeeH0XajTMbrvO86+0"
    "sU5RaCkrw+ctZ4mu47Gp6P4JsoaBANK5HMF4DH8uR1BKDg4N8W40jsRiEVBVVMRoOu8stFnb"
    "HOc2oHrHs38abPSUNGwOR1h6441sHxnhna4uOHaskI3Z4nSCEJRXV/GQw0GTf4I3T/fjbrki"
    "e1EAwAG4bll59UfVrVc3XHv7D/gwm2d3Qz2fNDXx30iEfd3dBIaHIR4/x1jt8uW01tSwXtOo"
    "8/tJJdPctaCUW3WV1v4hlZXXnLNmbhsKgI0//tFP6nUnXOnje18OMtL9BdWdnfw8GmXf6tVs"
    "Xb36HEOPbNzIbp+P70+Mk/28m/6BIX5XbCOyrBHPVIyR0RHvTJTFhQAA7Jvvu3///kMfc5Vv"
    "GeL6Fp6bHMdmGHSN++lsbyfe1weaxtmWwqOjHD96lJ54Ai0ZZ6/LQbhlJVcUOUmmkwwPDVQI"
    "Ibxzfc4FkIB5qrtryGbTSKRTrKqu5PANLXSM+CnN5slJSQ5A02YtTBgGpqKgGQanQiE+XXMd"
    "V5VV4HJ7yAvB6OkvBVDKnLTPBcgBwRtbW1Nr164lHonhQWOpz8euxRXk+vpJBiaRpgmqiqqq"
    "X+XOsshnMjA+zid1i6hdthQzlsDjLcVIpQkEA4ICMhfAAuLLl1/u6u/txe1xUb6gggZNo9fj"
    "pvjOO7ls3XpCfv90Cs5KpzBNiMXoBep+8TO+feUqGhovoaKijGAoSDQcBjgHohBAuKuro6Ht"
    "lVepr6vHW1qKU9VZ5Gtg92AvXqGQBlAUOAsgmUySyeVI2u0sbLmKxMQEmZxBkb2IWDRO2jC0"
    "GX/nL0IppQk4X3tj11uxRAxnWQnRaByHXaexeiHt4SB7217G5XaDosyypElJChDXXgNmnmzG"
    "IJFM0TPQB4qCDMf6mW7z8wPMtEgJMHb80OFPlUweqesIIfCoKtoVy0kAIpWatXsAzeGYLs4V"
    "l6EZBrl8jngmjUvV+OLQkUAwFHoN8F4QYGZSAqVYVnTn089mhJGhakkdWs7EWVGJH9CNPCgC"
    "aVn/X5gxDBSguMlHOhgkqymU6DpvP/cChmGEATvTRW5eKAUWEANOzmjvX3//WMaYirGwsR6b"
    "aiPqKka1cmBanP0llYaBHUgKkywS4hle3PZ0BugGDgNHgDEgf6EIAESAz4BXZ/TgH+69L5iN"
    "JVlcv4hsedn0FkxzFoCVNsgDWU1DJlL8+aGHQ8BB4BXgb8AHwNhMnZ0fQE5LCDgK/AP4O7Dn"
    "qd9uHfI4irEtqpoGsCzMswAUm4Zl17A7HDy75cFhYA/w0gzAx1LKCSllfq6/i14egSrgNuCP"
    "1FQOPfjD2+U9IPG4JdP1IgG5uapK7lxYLUWTbxh4GvgusOCi9udzg2W6M9YBj9badX+zokhU"
    "dRbASk2TK2AceBxYD3jnY7vgL1khEUKUAN8CVgDLABdftZQE4kAfcAL4XEoZm4/d/wG1QXtr"
    "GbVm7AAAAABJRU5ErkJggg==")

clone_jango_32_data = jango32.GetData
clone_jango_32_image = jango32.GetImage
clone_jango_32_bitmap = jango32.GetBitmap
clone_jango_32_icon = jango32.GetIcon
